/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import javax.swing.JOptionPane;
import clases.cliente;
import dao.daoCliente;
import javax.swing.table.DefaultTableModel;
public class frmCliente extends javax.swing.JFrame {

    daoCliente ocli = new daoCliente("cliente.txt");
     DefaultTableModel dtmCliente = new DefaultTableModel();
    public frmCliente() {
        initComponents();
        llenaCabecera();
        bloquear_estado(false);
        btnIngresar.setEnabled(false);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCliente = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATOS DE CLIENTE");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre");

        jLabel4.setText("RUC/DNI");

        tCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tClienteMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tCliente);

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGrabar.setText("GRABAR");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario)
                            .addComponent(txtDir)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrabar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
      this.bloquear_estado(true);
        txtRuc.requestFocus();//el puntero del mouse sobre la caja de texto
        limpiar();//Limpiar las cajas de texto
        txtRuc.setText("");
       bloquear_controles1();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
    int msg = JOptionPane.showConfirmDialog(this,"Deseas Grabar a este Cliente","Grabar",JOptionPane.YES_NO_OPTION);
    if(msg == JOptionPane.YES_OPTION){
        cliente a = new cliente(getNombre(),getCodigo(),getRucdni());
        ocli.adicionar(a);
        listar();
        ocli.grabar();//Grabar datos al archivo
        JOptionPane.showMessageDialog(this,"Cliente Grabado Satisfactoriamente!!!");
        btnIngresar.setEnabled(true);
    }
    else
    {
        txtUsuario.setText("");
         txtDir.setText("");
         txtUsuario.requestFocus();
    }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int msg = JOptionPane.showConfirmDialog(this,"Deseas Eliminar al Cliente","Eliminar",JOptionPane.YES_NO_OPTION);
        if(msg == JOptionPane.YES_OPTION){
            cliente a = ocli.buscar(getNombre());
            ocli.eliminar(a);
            listar();
            ocli.grabar();//Grabar datos al archivo
            JOptionPane.showMessageDialog(this,"Cliente Eliminado!!!","Mensaje",2);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     txtRuc.setEnabled(true);
    if(txtRuc.getText().equals("")){
        txtRuc.requestFocus();
    }else{
    int msg = JOptionPane.showConfirmDialog(this,"Deseas Buscar al Cliente","Buscar",JOptionPane.YES_NO_OPTION);    
    if(msg == JOptionPane.YES_OPTION){
        cliente a = ocli.buscar(getNombre());
        if(a == null){
            JOptionPane.showMessageDialog(this,"No se encuentro!!!");
            this.txtRuc.requestFocus();
        }else{
            txtRuc.setText("" + a.getRuc());
            txtUsuario.setText(a.getEmpresa());
            txtDir.setText(""+a.getDir());
        }
    }
    else{
    
    }
    bloquear_controles2();
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
    
        frmFactura1 frm  = new frmFactura1();
            dispose();
            frm.setVisible(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
    dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tClienteMousePressed
        if(evt.getClickCount()==2){
//            frmFactura fac = new frmFactura();
            int fil=tCliente.getSelectedRow();
            
            String m,n,ñ;
            m=tCliente.getValueAt(fil, 0).toString();
            n=tCliente.getValueAt(fil, 1).toString();
            ñ=tCliente.getValueAt(fil, 2).toString();
            
            frmFactura1.txtruc.setText(m);
            frmFactura1.txtEmpresa.setText(n);
            frmFactura1.txtDir.setText(ñ);
            this.dispose();    
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tClienteMousePressed
 
//BLOQUEAR ESTADOS
    public void bloquear_estado(boolean estado){
       this.txtRuc.setEnabled(estado);
       this.txtUsuario.setEnabled(estado);
       this.txtDir.setEnabled(estado);
    }
    public void bloquear_controles1(){
       btnNuevo.setEnabled(false);
       btnBuscar.setEnabled(true);
       btnIngresar.setEnabled(false);
       btnGrabar.setEnabled(true);
       btnEliminar.setEnabled(false);
   }
    public void bloquear_controles2(){
       btnNuevo.setEnabled(true);
       btnBuscar.setEnabled(true);
       btnIngresar.setEnabled(true);
       btnGrabar.setEnabled(false);
       btnEliminar.setEnabled(true);
   }
    //BLOQUEAR FIN
    public void llenaCabecera(){
      dtmCliente.addColumn("Ruc");
      dtmCliente.addColumn("Nombre");
      dtmCliente.addColumn("Direccion");
      
      tCliente.setModel(dtmCliente);
    }
    public void listar(){
    if(ocli.tamaño() == 0){
      JOptionPane.showMessageDialog(this,"Lista sin elementos!!!","Validar",2);
    }else{    
      dtmCliente.setRowCount(0);//Limpia las filas del JTable
      for(int i=0;i<ocli.tamaño();i++){
         Object vec[]=new Object[3];
         vec[0] = ocli.obtener(i).getRuc();
         vec[1] = ocli.obtener(i).getEmpresa();
         vec[2] = ocli.obtener(i).getDir();
         
         //agregar al JTable
         dtmCliente.addRow(vec);
      }
      tCliente.setModel(dtmCliente);
    }
    }
     public void limpiar(){
        this.txtRuc.setText("");
        this.txtUsuario.setText("");
        this.txtDir.setText("");
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }
    public long getCodigo()         {return Long.parseLong(txtRuc.getText());}
    public String getNombre()   {return txtUsuario.getText();}
    public String getRucdni() {return txtDir.getText();}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tCliente;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
