/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import ConexionBD.Conexion;
import dao.daoPlato;
import dao.daoMesa;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import modelo.Colorear_filas;

/**
 *
 * @author Luigi ga
 */
public class frmDelibery extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarPedido
     */
    Conexion conexion;
    daoPlato daoPla = new daoPlato();
    daoMesa daoMes = new daoMesa();
    Colorear_filas color_fila = new Colorear_filas();
    int filaseleccionada;
    String cantidad;
    DefaultTableModel dtmPlato = new DefaultTableModel();
    DefaultTableModel dtmPedido = new DefaultTableModel();
    
    public frmDelibery() {
        initComponents();
        cargarCabeceraTablePedido();
        daoPla.cargarCategoriaPlato(cboCategoriaPlato);
        cargarCabeceraTablePlato();
        
        this.setLocationRelativeTo(null);
    }
    
    public void Ocultar_plato()
    {
        jtPlato.getColumnModel().getColumn(0).setMaxWidth(0);
        jtPlato.getColumnModel().getColumn(0).setMinWidth(0);
        jtPlato.getColumnModel().getColumn(0).setPreferredWidth(0);
        jtPlato.getColumnModel().getColumn(3).setMaxWidth(0);
        jtPlato.getColumnModel().getColumn(3).setMinWidth(0);
        jtPlato.getColumnModel().getColumn(3).setPreferredWidth(0);
        jtPlato.getColumnModel().getColumn(4).setMaxWidth(0);
        jtPlato.getColumnModel().getColumn(4).setMinWidth(0);
        jtPlato.getColumnModel().getColumn(4).setPreferredWidth(0);

        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboCategoriaPlato = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPlato = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtPedido = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        btnEliminarPedido = new javax.swing.JButton();
        btnAgregarPedido = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Delibery");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Categoria de Plato :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        cboCategoriaPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCategoriaPlato.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCategoriaPlatoItemStateChanged(evt);
            }
        });
        getContentPane().add(cboCategoriaPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 140, -1));

        jLabel5.setText("Mesero :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 41, 170, 40));

        jtPlato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtPlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPlatoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtPlato);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 320, 380));

        jtPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtPedido);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 56, 360, 388));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pedido");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 360, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 11, 10, 501));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/machis/cerrar.png"))); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 150, -1));

        btnEliminarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/machis/remove.png"))); // NOI18N
        btnEliminarPedido.setText("Remover");
        btnEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 150, -1));

        btnAgregarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/machis/add.png"))); // NOI18N
        btnAgregarPedido.setText("Agregar");
        btnAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 150, -1));

        jLabel7.setText("Cantidad :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 60, 20));
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtPlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPlatoMouseClicked
        // TODO add your handling code here:
        
//        try {
//            filaseleccionada = jtPlato.getSelectedRow();
//            if(filaseleccionada == -1){
//                JOptionPane.showMessageDialog(this,"No se ha seleccionado ninguna fila","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
//            }
//            else{
//                //dtmPedido.setRowCount(0);
//                dtmPedido = (DefaultTableModel) jtPedido.getModel();
//                String filaelemento[] = {
//                    jtPlato.getValueAt(filaseleccionada, 0).toString(),
//                    jtPlato.getValueAt(filaseleccionada, 0).toString(),
//                    jtPlato.getValueAt(filaseleccionada, 0).toString()
//                };
//                dtmPedido.addRow(filaelemento);
//                System.out.println(jtPlato.getValueAt(filaseleccionada, 0).toString());
//            }
//        } catch (Exception e) {
//        }
    }//GEN-LAST:event_jtPlatoMouseClicked

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
        // TODO add your handling code here:
        try {
            filaseleccionada = jtPlato.getSelectedRow();
            double importe;
            if(filaseleccionada == -1){
                JOptionPane.showMessageDialog(this,"No se ha seleccionado ninguna fila","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                //dtmPedido.setRowCount(0);
                cantidad = txtcantidad.getText();
                if(cantidad.length()==0){
                    JOptionPane.showMessageDialog(this,"No se ha introducido una cantidad","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
                }
                else{
                    importe = (Integer.parseInt(cantidad) * Double.parseDouble(jtPlato.getValueAt(filaseleccionada, 1).toString()));
                    dtmPedido = (DefaultTableModel) jtPedido.getModel();
                    String filaelemento[] = {
                        cantidad,
                        jtPlato.getValueAt(filaseleccionada, 0).toString(),
                        jtPlato.getValueAt(filaseleccionada, 1).toString(),
                        String.valueOf(importe)
                    };
                    dtmPedido.addRow(filaelemento);
                    System.out.println(jtPlato.getValueAt(filaseleccionada, 0).toString());
                }
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    private void btnEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPedidoActionPerformed
        // TODO add your handling code here:
        int respuesta ;
        int fila;
        try {
            filaseleccionada = jtPlato.getSelectedRow();
            double importe;
            if(filaseleccionada == -1){
                JOptionPane.showMessageDialog(this,"No se ha seleccionado ninguna fila a eliminar","Mensaje del Sistema",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                //dtmPedido.setRowCount(0);
                respuesta = JOptionPane.showConfirmDialog(null, "¿ Estas seguro de eliminar este plato del pedido ?","Eliminar",JOptionPane.YES_NO_OPTION); 
                if (respuesta==JOptionPane.YES_OPTION) {
                    dtmPedido = (DefaultTableModel) jtPedido.getModel();
                    dtmPedido.removeRow(filaseleccionada);
                }
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se realizo la eliminacion del plato, verifique.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarPedidoActionPerformed

    private void cboCategoriaPlatoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCategoriaPlatoItemStateChanged
        // TODO add your handling code here:
        daoPla.cargar_tabla(dtmPlato, jtPlato, cboCategoriaPlato.getSelectedItem().toString());
    }//GEN-LAST:event_cboCategoriaPlatoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDelibery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDelibery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDelibery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDelibery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDelibery().setVisible(true);
            }
        });
    }
   
    public void cargarCabeceraTablePedido(){ 
        dtmPedido.addColumn("Plato"); 
        dtmPedido.addColumn("Cantidad"); 
        dtmPedido.addColumn("Descripcion"); 
        dtmPedido.addColumn("Precio");
        dtmPedido.addColumn("Importe");
        
        
        jtPedido.setModel(dtmPedido);
    }
    
    
    public void cargarCabeceraTablePlato(){
        dtmPlato.addColumn("ID Plato"); 
        dtmPlato.addColumn("Nombre de Plato"); 
        dtmPlato.addColumn("Precio"); 
        dtmPlato.addColumn("Estado");
        dtmPlato.addColumn("Categoria de Plato"); 
        jtPlato.setModel(dtmPlato);
    }
   
       
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPedido;
    private javax.swing.JButton btnEliminarPedido;
    private javax.swing.JComboBox<String> cboCategoriaPlato;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtPedido;
    private javax.swing.JTable jtPlato;
    private javax.swing.JTextField txtcantidad;
    // End of variables declaration//GEN-END:variables
}
