/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import dao.pdf;
import dao.daofacturas;
import clases.fact;
import clases.factura;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.daoFactura;

/**
 *
 * @author 
 */
public class frmFactura1 extends javax.swing.JFrame {

    SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form frmFactura1
     */

    
    daoFactura oven = new daoFactura();
    daofacturas fa=new daofacturas("facturas.txt");
    pdf pdf=new pdf();
    DefaultTableModel dtmVenta = new DefaultTableModel();
    public frmFactura1() {
        initComponents();
        llenaCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomE = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tventa = new javax.swing.JTable();
        txtEmpresa = new javax.swing.JTextField();
        numeroruc = new javax.swing.JLabel();
        factura = new javax.swing.JLabel();
        rucE = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPro = new javax.swing.JTextField();
        direccion = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        subtotal = new javax.swing.JLabel();
        igv = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        dirE = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        btnElegirEmpresa = new javax.swing.JButton();
        btnElegirProducto = new javax.swing.JButton();
        datoFecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        txtIgv = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomE.setText("NOMBRE DE LA EMPRESA:");
        getContentPane().add(nomE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        tventa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tventa);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, 122));
        getContentPane().add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 148, -1));

        numeroruc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numeroruc.setText("RUC: 20248454753");
        getContentPane().add(numeroruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        factura.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        factura.setText("Factura");
        getContentPane().add(factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        rucE.setText("RUC: ");
        getContentPane().add(rucE, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel7.setText("Cantidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, -1, -1));
        getContentPane().add(txtPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 105, -1));

        direccion.setText("Av.Agelica Gamarra 949 - Los  Olivos");
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titulo.setText("REMOLINO DEL PEZ");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(txtruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 148, -1));

        jLabel11.setText("Producto");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));
        getContentPane().add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 38, -1));

        subtotal.setText("total:");
        getContentPane().add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 182, 20));

        igv.setText("IGV:");
        getContentPane().add(igv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 182, 20));

        total.setText("total");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 182, 20));

        jLabel3.setText("S/");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));
        getContentPane().add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 60, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_seguir-comprando.jpg"))); // NOI18N
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 184, -1));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_eliminar-compra.jpg"))); // NOI18N
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 163, 35));

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_cerrar.jpg"))); // NOI18N
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 80, 36));

        dirE.setText("Direccion:");
        getContentPane().add(dirE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));
        getContentPane().add(txtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 148, -1));

        btnGenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/button_facturar.jpg"))); // NOI18N
        btnGenerar.setContentAreaFilled(false);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 96, 36));

        jLabel13.setText("precios sin igv");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 38, -1));

        btnElegirEmpresa.setText("ELEGIR EMPRESA");
        btnElegirEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(btnElegirEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 192, -1));

        btnElegirProducto.setText("ELEGIR PRODUCTO");
        btnElegirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirProductoActionPerformed(evt);
            }
        });
        getContentPane().add(btnElegirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 192, -1));
        getContentPane().add(datoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 140, -1));

        jLabel1.setText("codigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel2.setText("Stock:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));
        getContentPane().add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 50, -1));

        txtIgv.setText("0.18");
        txtIgv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIgvActionPerformed(evt);
            }
        });
        getContentPane().add(txtIgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 40, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("IGV:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 40, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoFactura.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        factura a= new factura(getCod(),getPro(),getPrecio(),getCantidad(),getPrecio()*getCantidad());
        oven.adicionar(a);
        oven.grabar(getEmpresa()+".txt");
        listar();
        //cargarCliente();

        //        limpiar();//Limpiar las cajas de text
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int msg = JOptionPane.showConfirmDialog(this,"Deseas Eliminar el Registro","Eliminar",JOptionPane.YES_NO_OPTION);
        if(msg == JOptionPane.YES_OPTION){
            factura a = oven.buscar(getCod());
            oven.eliminar(a);
            listar();
            oven.grabar(getEmpresa()+".txt");//Grabar datos al archivo
            //listar();
            JOptionPane.showMessageDialog(this,"Registro Eliminado!!!","Mensaje",2);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
        String fechaNac=formatoDelTexto.format(datoFecha.getDate());
        
        int msg = JOptionPane.showConfirmDialog(this,"Deseas Grabar el Registro","Grabar",JOptionPane.YES_NO_OPTION);
        if(msg == JOptionPane.YES_OPTION){
            factura a  = new factura(getCod(),getPro(),getPrecio(),getCantidad(),getPrecio()*getCantidad());
            
            listar();
            oven.grabar("facturas\\"+getEmpresa()+".txt");//Grabar datos al archivo

                JOptionPane.showMessageDialog(this,"Registro Grabado Satisfactoriamente!!!");
                try
            {
                Paragraph parrafo;
                Document doc=new Document(PageSize.LETTER , 36, 36, 54, 36);
                FileOutputStream archivo=new FileOutputStream("pdf\\"+getEmpresa()+".pdf");
                    PdfWriter writer=PdfWriter.getInstance(doc,archivo);
                    doc.open();
                    Image imagen2= Image.getInstance("src\\imagenes\\marca.jpg");
                    imagen2.scaleAbsolute(500,500);
                    imagen2.setAbsolutePosition(55f, 130f);
                    doc.add(imagen2);
                    Image imagen= Image.getInstance("src\\imagenes\\logo.jpg");
                    imagen.scaleAbsolute(100,100);
                    imagen.setAbsolutePosition(50f, 650f);
                    doc.add(imagen);
                    Image imagen1= Image.getInstance("src\\imagenes\\factura.jpg");
                    imagen1.scaleAbsolute(100,100);
                    imagen1.setAbsolutePosition(470f, 650f);
                    doc.add(imagen1);

                    // pdf p= pdf.getcabezera(titulo.getText()+"\n"+numeroruc.getText()+"\n"+direccion.getText()).setAlignment(Element.ALIGN_JUSTIFIED);

                    Paragraph p=pdf.getcabezera(titulo.getText()+"\n\n\n"+numeroruc.getText());
                    p.setAlignment(Element.ALIGN_CENTER);
                    doc.add(p);
                    p=pdf.getContenido("\n\n\nfecha:"+fechaNac);
                    p.setAlignment(Element.ALIGN_RIGHT);
                    doc.add(p);
                    p=pdf.getContenido("\n\n"+nomE.getText()+" "+txtEmpresa.getText()+"\n\n"+rucE.getText()+" "+txtruc.getText()+"\n\n"+dirE.getText()+" "+txtDir.getText()+"\n\n\n");
                    p.setAlignment(Element.ALIGN_LEFT);
                    doc.add(p);

                    PdfPTable table = new PdfPTable(5);
                    // addCell() agrega una celda a la tabla, el cambio de fila
                    // ocurre automaticamente al llenar la fila
                    table.setWidthPercentage (100);

                    table.addCell("CODIGO");
                    table.addCell("PRODUCTO");

                    table.addCell("PRECIO");
                    table.addCell("CANTIDAD");
                    table.addCell("TOTAL");

                    for(int i=0;i<oven.tamaño();i++){
                        table.addCell(String.valueOf(oven.obtener(i).getCod()));
                        table.addCell(oven.obtener(i).getProd());
                        table.addCell(String.valueOf(oven.obtener(i).getPrecio()));
                        table.addCell(String.valueOf(oven.obtener(i).getCantidad()));
                        table.addCell(String.valueOf(oven.obtener(i).getPrecio()*oven.obtener(i).getCantidad()));
                    }
                    // Si desea crear una celda de mas de una columna
                    // Cree un objecto Cell y cambie su propiedad span
                    doc.add(table);

                    p=pdf.getUltimo("\n\n"+subtotal.getText()+"\n\n"+igv.getText()+"\n\n"+total.getText());
                    p.setAlignment(Element.ALIGN_RIGHT);
                    doc.add(p);

                    doc.add(pdf.getBarcode(doc, writer, String.valueOf(getRuc())));

                    Image imagen3= Image.getInstance("src\\imagenes\\pagado.jpg");
                    imagen3.scaleAbsolute(100,100);
                    imagen3.setAbsolutePosition(470f, 170f);
                    doc.add(imagen3);

                    doc.close();
                    JOptionPane.showMessageDialog(null,"Pdf correctamente creado");
                }catch(Exception e){
                    System.out.println("error: "+e);

                }
                fact n=new fact(fa.getCorrelativoAcc(),getEmpresa(),, fechaNac, fechaNac);
                
                
            }
            else
            {

                listar();

            }

            

                frmFactura1 f=new frmFactura1();
                f.setVisible(true);
                dispose();
                // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnElegirEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirEmpresaActionPerformed
        frmCliente cli =new frmCliente();
        cli.setVisible(true);
    }//GEN-LAST:event_btnElegirEmpresaActionPerformed

    private void btnElegirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirProductoActionPerformed
        frmProducto pro= new frmProducto();
        pro.setVisible(true);
    }//GEN-LAST:event_btnElegirProductoActionPerformed

    private void txtIgvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIgvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIgvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFactura1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFactura1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFactura1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFactura1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFactura1().setVisible(true);
            }
        });
    }
    
    public int getCod(){    return Integer.parseInt(txtCod.getText());}
      
    public String getEmpresa(){ return txtEmpresa.getText();}
    public long getRuc(){ return Long.parseLong(txtruc.getText());}
    public String getDireccion(){ return txtDir.getText();}    
    public String getPro(){ return txtPro.getText();}
    public double getPrecio(){ return Double.parseDouble(txtPrecio.getText());}
    public int getCantidad(){ return Integer.parseInt(txtCantidad.getText());}


    public void listar(){
    if(oven.tamaño() == 0){
      JOptionPane.showMessageDialog(this,"Lista sin elementos!!!","Validar",2);
          
    }else{    
      dtmVenta.setRowCount(0);//Limpia las filas del JTable
      for(int i=0;i<oven.tamaño();i++){
          Object vec[]=new Object[5];
          vec[0]=oven.obtener(i).getCod();
          vec[1] = oven.obtener(i).getProd();
          vec[2] = oven.obtener(i).getPrecio();
          vec[3] = oven.obtener(i).getCantidad();
          vec[4] = oven.obtener(i).getPrecio()*oven.obtener(i).getCantidad();
 
         //agregar al JTable
         dtmVenta.addRow(vec);
      }

      tventa.setModel(dtmVenta);
    }
      subtotal.setText("SUBTOTAL: s/" + oven.totalPension()+"0");
      igv.setText(String.format("IGV: s/(%.3f)", oven.igv(Double.parseDouble(txtIgv.getText()))));
      total.setText("TOTAL: s/"+oven.total(oven.igv(Double.parseDouble(txtIgv.getText()))));
    }
      public void llenaCabecera(){
          dtmVenta.addColumn("cod");
      dtmVenta.addColumn("producto");
      dtmVenta.addColumn("precio");
      dtmVenta.addColumn("cantidad");
      dtmVenta.addColumn("total a pagar");
      tventa.setModel(dtmVenta);
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnElegirEmpresa;
    private javax.swing.JButton btnElegirProducto;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnNuevo;
    private com.toedter.calendar.JDateChooser datoFecha;
    private javax.swing.JLabel dirE;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel factura;
    private javax.swing.JLabel igv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomE;
    private javax.swing.JLabel numeroruc;
    private javax.swing.JLabel rucE;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel total;
    private javax.swing.JTable tventa;
    public static javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCod;
    public static javax.swing.JTextField txtDir;
    public static javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtIgv;
    public static javax.swing.JTextField txtPrecio;
    public static javax.swing.JTextField txtPro;
    public static javax.swing.JTextField txtStock;
    public static javax.swing.JTextField txtruc;
    // End of variables declaration//GEN-END:variables
}
